name: AUTO_RUN_TEST

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      ENV_MODE: 'DEBUG'

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: test

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install python package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run API
      continue-on-error: true
      env:
        # GitHub 的账号信息
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        # 以下是微软的账号信息
        APP_NUM: ${{ secrets.APP_NUM }}
        MS_TOKEN: ${{ secrets.MS_TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        # 发送信息
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        # 持久化
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        : "${GH_TOKEN:?Environment variable GH_TOKEN is not set}"
        : "${MS_TOKEN:?Environment variable MS_TOKEN is not set}"
        : "${CLIENT_ID:?Environment variable CLIENT_ID is not set}"
        : "${CLIENT_SECRET:?Environment variable CLIENT_SECRET is not set}"
        python index.py
        chmod +x /tmp/github_mask.sh
        bash /tmp/github_mask.sh || true

    - name: Upload Log File to Server
      continue-on-error: true
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        LOG_SERVER_URL: ${{ secrets.LOG_SERVER_URL }}
      run: |
        if [ -z "$SSH_PRIVATE_KEY" ] || [ -z "$LOG_SERVER_URL" ]; then
          echo "!!!未配置日志服务器，该模式下无日志存档!!!"
          exit 0
        fi
        
        LOG_SERVER_USER="${LOG_SERVER_URL%%@*}"
        LOG_SERVER_HOST_PATH="${LOG_SERVER_URL#*@}"
        LOG_SERVER_HOST="${LOG_SERVER_HOST_PATH%%/*}"
        LOG_FILE_PATH="/${LOG_SERVER_HOST_PATH#*/}"

        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan "${LOG_SERVER_HOST}" 2>/dev/null | grep -v '^#' >> ~/.ssh/known_hosts
        
        LOG_DATE=$(date +'%m%d%H%M')
        mv ${LOG_FILENAME}.log ${LOG_FILENAME}_${LOG_DATE}.log

        scp -q ${LOG_FILENAME}_${LOG_DATE}.log "${LOG_SERVER_USER}@${LOG_SERVER_HOST}:${LOG_FILE_PATH}"
        
        echo "Log file uploaded successfully."

    - name: Post Process
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python utils.py --task PostProcess
